website: "www.midwestaccesscoalition.org"
street_1: 3052 W North Ave
street_2: "#2"
city: Chicago
state: IL
zip: 60647
full_address: "3052 W North Ave, #2, Chicago, IL 60647"
support_line: 847-750-6224
ein: 47-2160168
